name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "**"

jobs:
  quality:
    name: Lint ${{ matrix.project }} (Python ${{ matrix.python }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - project: "lab1"
            python: "3.11"
#          - project: "lab2"
#            python: "3.12"


    defaults:
      run:
        working-directory: ${{ matrix.project }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv + Python
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python }}
          install-python: true
          enable-cache: true

      - name: Install dependencies
        run: uv sync --frozen

      - name: Check formatting
        run: uv run ruff format --check .

      - name: Lint
        run: uv run ruff check .
